ComboBoxSearch: Fix an AttributeError in hidePopup
ComboBoxSearch(enabled=False) raised an:

```
Traceback (most recent call last):
  File "../orangewidget/utils/combobox.py", line 302, in hidePopup
    if self.__popup is not None:
AttributeError: 'ComboBoxSearch' object has no attribute '_ComboBoxSearch__popup'
```

Due to virtual override calls from within base QComboBox constructor